apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: php-apache
  namespace: default
spec:
  clusterIP: 100.65.9.72
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: php-apache
  sessionAffinity: None
  type: ClusterIP
